apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed
  labels:
    app: udagram-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-feed
  template:
    metadata:
      labels:
        app: udagram-feed
    spec:
      containers:
      - name: udagram-feed
        image: vmonrabal/udagram-feed
        envFrom: 
          - secretRef: 
              name: udagram-secrets
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret 
